services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    networks:
      - app-network

  front-end:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    networks:
      - app-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end
    networks:
      - app-network

networks:
  app-network:
    driver: bridge